name: 'Update changelog version'
description: 'Updates the changelog with the latest version and outputs commits in that release'
inputs:
  token:
    description: 'GitHub token'
    required: true
  filePath:
    description: 'Path to your changelog'
    required: true
  prefix:
    description: 'What commits need to start with in order to be included in the changelog output'
outputs:
  newTag:
    description: 'New tag for the release'
  changelog:
    description: 'The changes for the newest release'
runs:
  using: 'node12'
  main: 'dist/index.js'
