name: 'Update changelog version'
description: 'Updates the changelog with the latest version and outputs commits in that release'
inputs:
  filePath:
    description: 'Path to your changelog'
    required: true
  comparisonBranch:
    description: 'Branch to compare to when checking what commits went into the release'
outputs:
  newTag:
    description: 'New tag for the release'
  changelog:
    description: 'The changes for the newest release'
runs:
  using: 'node12'
  main: 'dist/index.js'
